  - name: creat roboshop user
    ansible.builtin.user:
      name: roboshop

  - name: recursively remove app
    ansible.builtin.file:
      path: /app
      state: absent

  - name: creat a directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: "download {{component}} app"
    ansible.builtin.get_url:
      url: "https://roboshop-builds.s3.amazonaws.com/{{component}}.zip"
      dest: /tmp

  - name: "extract {{component}} application"
    ansible.builtin.unarchive:
      src: /tmp/{{component}}.zip
      dest: /app
      remote_src: yes