  - name: "integrating mongo to {{component}} server"
    ansible.builtin.template:
      src: "{{component}}.service.j2"
      dest: "/etc/systemd/system/{{component}}.service"

  - name: reloading the daemon
    ansible.builtin.systemd_service:
      daemon_reload: true

  - name: "{{component}} service enable and start"
    ansible.builtin.service:
      name: {{component}}
      state: restarted
      enabled: yes