  - name: integrating mongo to catalogue server
    ansible.builtin.copy:
      src: catalogue.service
      dest: /etc/systemd/system/catalogue.service

  - name: reloading the daemon
    ansible.builtin.systemd_service:
      daemon_reload: true

  - name: catlogue service enable and start
    ansible.builtin.service:
      name: catalogue
      state: restarted
      enabled: yes